import {
  AdminInternship,
  AdminApplication,
  AdminStudent,
  AdminCompany,
  AdminEvent,
  AdminDashboardStats,
} from "./types";

// Mock Dashboard Stats
export const mockAdminStats: AdminDashboardStats = {
  totalStudents: 245,
  totalCompanies: 32,
  totalInternships: 87,
  pendingInternships: 12,
  totalApplications: 156,
  pendingApplications: 43,
  activeEvents: 1,
};

// Mock Internships for Admin
export const mockAdminInternships: AdminInternship[] = [
  {
    id: 1,
    title: "Full Stack Developer Intern",
    description: "Build modern web applications",
    field: "Web Development",
    location: "Casablanca",
    duration: "3 months",
    workMode: "hybrid",
    status: "approved",
    createdAt: new Date("2026-01-15"),
    applicationsCount: 12,
    company: {
      id: 1,
      name: "TechCorp",
      logoUrl: null,
    },
  },
  {
    id: 2,
    title: "Data Science Intern",
    description: "Work with ML models and analytics",
    field: "Data Science",
    location: "Rabat",
    duration: "6 months",
    workMode: "on_site",
    status: "pending",
    createdAt: new Date("2026-01-28"),
    applicationsCount: 0,
    company: {
      id: 2,
      name: "DataFlow Solutions",
      logoUrl: null,
    },
  },
  {
    id: 3,
    title: "DevOps Engineer Intern",
    description: "Manage CI/CD pipelines",
    field: "DevOps",
    location: "Remote",
    duration: "4 months",
    workMode: "remote",
    status: "pending",
    createdAt: new Date("2026-01-30"),
    applicationsCount: 0,
    company: {
      id: 3,
      name: "CloudNine Tech",
      logoUrl: null,
    },
  },
  {
    id: 4,
    title: "Mobile Developer Intern",
    description: "Build cross-platform mobile apps",
    field: "Mobile Development",
    location: "Marrakech",
    duration: "3 months",
    workMode: "hybrid",
    status: "pending",
    createdAt: new Date("2026-01-31"),
    applicationsCount: 0,
    company: {
      id: 4,
      name: "AppWorks Studio",
      logoUrl: null,
    },
  },
  {
    id: 5,
    title: "UI/UX Design Intern",
    description: "Design beautiful user interfaces",
    field: "UI/UX Design",
    location: "Casablanca",
    duration: "3 months",
    workMode: "on_site",
    status: "approved",
    createdAt: new Date("2026-01-10"),
    applicationsCount: 8,
    company: {
      id: 5,
      name: "Creative Labs",
      logoUrl: null,
    },
  },
  {
    id: 6,
    title: "Backend Developer Intern",
    description: "Build scalable APIs",
    field: "Backend Development",
    location: "Tangier",
    duration: "6 months",
    workMode: "hybrid",
    status: "rejected",
    createdAt: new Date("2026-01-05"),
    applicationsCount: 0,
    company: {
      id: 1,
      name: "TechCorp",
      logoUrl: null,
    },
  },
];

// Mock Applications for Admin
export const mockAdminApplications: AdminApplication[] = [
  {
    id: 1,
    internship: {
      id: 1,
      title: "Full Stack Developer Intern",
      company: { id: 1, name: "TechCorp" },
    },
    applicant: {
      id: 101,
      firstName: "Ahmed",
      lastName: "Benali",
      email: "ahmed.benali@university.ma",
      universityId: "STU2024001",
      fieldOfStudy: "Computer Science",
    },
    status: "pending",
    appliedAt: new Date("2026-01-30"),
    reviewedAt: null,
  },
  {
    id: 2,
    internship: {
      id: 1,
      title: "Full Stack Developer Intern",
      company: { id: 1, name: "TechCorp" },
    },
    applicant: {
      id: 102,
      firstName: "Fatima",
      lastName: "Zahra",
      email: "fatima.zahra@university.ma",
      universityId: "STU2024002",
      fieldOfStudy: "Software Engineering",
    },
    status: "accepted",
    appliedAt: new Date("2026-01-25"),
    reviewedAt: new Date("2026-01-28"),
  },
  {
    id: 3,
    internship: {
      id: 5,
      title: "UI/UX Design Intern",
      company: { id: 5, name: "Creative Labs" },
    },
    applicant: {
      id: 103,
      firstName: "Youssef",
      lastName: "El Amrani",
      email: "youssef.elamrani@university.ma",
      universityId: "STU2024003",
      fieldOfStudy: "Graphic Design",
    },
    status: "pending",
    appliedAt: new Date("2026-01-29"),
    reviewedAt: null,
  },
  {
    id: 4,
    internship: {
      id: 1,
      title: "Full Stack Developer Intern",
      company: { id: 1, name: "TechCorp" },
    },
    applicant: {
      id: 104,
      firstName: "Sara",
      lastName: "Idrissi",
      email: "sara.idrissi@university.ma",
      universityId: "STU2024004",
      fieldOfStudy: "Computer Science",
    },
    status: "rejected",
    appliedAt: new Date("2026-01-22"),
    reviewedAt: new Date("2026-01-26"),
  },
];

// Mock Students for Admin
export const mockAdminStudents: AdminStudent[] = [
  {
    id: 101,
    firstName: "Ahmed",
    lastName: "Benali",
    email: "ahmed.benali@university.ma",
    universityId: "STU2024001",
    fieldOfStudy: "Computer Science",
    cvUrl: "/cv/ahmed-benali.pdf",
    createdAt: new Date("2025-09-01"),
    applicationsCount: 3,
  },
  {
    id: 102,
    firstName: "Fatima",
    lastName: "Zahra",
    email: "fatima.zahra@university.ma",
    universityId: "STU2024002",
    fieldOfStudy: "Software Engineering",
    cvUrl: "/cv/fatima-zahra.pdf",
    createdAt: new Date("2025-09-05"),
    applicationsCount: 5,
  },
  {
    id: 103,
    firstName: "Youssef",
    lastName: "El Amrani",
    email: "youssef.elamrani@university.ma",
    universityId: "STU2024003",
    fieldOfStudy: "Data Science",
    cvUrl: "/cv/youssef-elamrani.pdf",
    createdAt: new Date("2025-09-10"),
    applicationsCount: 2,
  },
  {
    id: 104,
    firstName: "Sara",
    lastName: "Idrissi",
    email: "sara.idrissi@university.ma",
    universityId: "STU2024004",
    fieldOfStudy: "Computer Science",
    cvUrl: null,
    createdAt: new Date("2025-10-01"),
    applicationsCount: 4,
  },
  {
    id: 105,
    firstName: "Omar",
    lastName: "Benjelloun",
    email: "omar.benjelloun@university.ma",
    universityId: "STU2024005",
    fieldOfStudy: "Mathematics",
    cvUrl: "/cv/omar-benjelloun.pdf",
    createdAt: new Date("2025-10-15"),
    applicationsCount: 1,
  },
];

// Mock Companies for Admin
export const mockAdminCompanies: AdminCompany[] = [
  {
    id: 1,
    name: "TechCorp",
    email: "hr@techcorp.ma",
    description: "Leading technology company in Morocco",
    website: "https://techcorp.ma",
    logoUrl: null,
    createdAt: new Date("2025-06-01"),
    internshipsCount: 5,
    activeInternshipsCount: 2,
  },
  {
    id: 2,
    name: "DataFlow Solutions",
    email: "contact@dataflow.ma",
    description: "Data analytics and machine learning solutions",
    website: "https://dataflow.ma",
    logoUrl: null,
    createdAt: new Date("2025-07-15"),
    internshipsCount: 3,
    activeInternshipsCount: 1,
  },
  {
    id: 3,
    name: "CloudNine Tech",
    email: "jobs@cloudnine.ma",
    description: "Cloud infrastructure and DevOps services",
    website: "https://cloudnine.ma",
    logoUrl: null,
    createdAt: new Date("2025-08-01"),
    internshipsCount: 2,
    activeInternshipsCount: 0,
  },
  {
    id: 4,
    name: "AppWorks Studio",
    email: "hello@appworks.ma",
    description: "Mobile app development studio",
    website: "https://appworks.ma",
    logoUrl: null,
    createdAt: new Date("2025-09-01"),
    internshipsCount: 4,
    activeInternshipsCount: 2,
  },
  {
    id: 5,
    name: "Creative Labs",
    email: "design@creativelabs.ma",
    description: "UI/UX design agency",
    website: "https://creativelabs.ma",
    logoUrl: null,
    createdAt: new Date("2025-10-01"),
    internshipsCount: 2,
    activeInternshipsCount: 1,
  },
];

// Mock Events for Admin
export const mockAdminEvents: AdminEvent[] = [
  {
    id: 1,
    name: "Career Forum 2026",
    description: "Annual career forum connecting students with companies",
    slogan: "Bridge to Your Future",
    year: 2026,
    startDate: new Date("2026-03-15"),
    endDate: new Date("2026-03-17"),
    location: "ENSIAS, Rabat",
    isActive: true,
    createdAt: new Date("2025-12-01"),
    internshipsCount: 45,
    companiesCount: 20,
  },
  {
    id: 2,
    name: "Career Forum 2025",
    description: "Career forum for the year 2025",
    slogan: "Connect & Grow",
    year: 2025,
    startDate: new Date("2025-03-10"),
    endDate: new Date("2025-03-12"),
    location: "ENSIAS, Rabat",
    isActive: false,
    createdAt: new Date("2024-12-01"),
    internshipsCount: 38,
    companiesCount: 18,
  },
  {
    id: 3,
    name: "Career Forum 2024",
    description: "Career forum for the year 2024",
    slogan: "Your Career Starts Here",
    year: 2024,
    startDate: new Date("2024-03-08"),
    endDate: new Date("2024-03-10"),
    location: "ENSIAS, Rabat",
    isActive: false,
    createdAt: new Date("2023-12-01"),
    internshipsCount: 32,
    companiesCount: 15,
  },
];
